# Generated by Django 5.1.4 on 2025-01-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_owner', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('model_description', models.TextField()),
                ('model_version', models.IntegerField(default=0)),
            ],
        ),
    ]
